name: Update README ⭐
on:
  push:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2313413
          leaderboardId: 1711139
          sessionCookie: ${{ secrets.AOC_SESSION_COOKIE }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README