apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-app
spec:
  automountServiceAccountToken: false
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
      resources:
        limits:
          memory: 100Mi
          cpu: 0.5
