apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    name: app-deploy
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-pod
      app: demo-app
  template:
    metadata:
      name: app-pod
      labels:
        name: app-pod
        app: demo-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          resources:
            limits:
              memory: 100Mi
              cpu: 0.5
          ports:
            - containerPort: 80