apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres
          resources:
            limits:
              memory: 100Mi
              cpu: 0.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"