apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
          resources:
            limits:
              memory: 100Mi
              cpu: 0.5