PREFIX : <URL>
PREFIX inst: <URL>

#Top movies by it's price

SELECT distinct ?title ?price
WHERE {
    ?movie a inst:Movie;
    mdb:title ?title;
    mdb:price ?price;
} ORDER BY DESC (?price)
  LIMIT 10