

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_320870677764563 = Integer(320870677764563); _sage_const_40 = Integer(40); _sage_const_335750934489987 = Integer(335750934489987); _sage_const_24 = Integer(24); _sage_const_282502845957937 = Integer(282502845957937); _sage_const_10 = Integer(10); _sage_const_219235623600942 = Integer(219235623600942); _sage_const_127 = Integer(127); _sage_const_408022798608755 = Integer(408022798608755); _sage_const_45 = Integer(45); _sage_const_245679379684914 = Integer(245679379684914); _sage_const_66 = Integer(66); _sage_const_171834827764229 = Integer(171834827764229); _sage_const_122 = Integer(122); _sage_const_225154401936948 = Integer(225154401936948); _sage_const_521 = Integer(521); _sage_const_232302441670972 = Integer(232302441670972); _sage_const_95 = Integer(95)
var('x y z vx vy vz t1 t2 t3 ans')
eq1 = x + (vx * t1) == _sage_const_320870677764563  + (-_sage_const_40  * t1)
eq2 = y + (vy * t1) == _sage_const_335750934489987  + (-_sage_const_24  * t1)
eq3 = z + (vz * t1) == _sage_const_282502845957937  + (_sage_const_10  * t1)
eq4 = x + (vx * t2) == _sage_const_219235623600942  + (_sage_const_127  * t2)
eq5 = y + (vy * t2) == _sage_const_408022798608755  + (-_sage_const_45  * t2)
eq6 = z + (vz * t2) == _sage_const_245679379684914  + (_sage_const_66  * t2)
eq7 = x + (vx * t3) == _sage_const_171834827764229  + (-_sage_const_122  * t3)
eq8 = y + (vy * t3) == _sage_const_225154401936948  + (-_sage_const_521  * t3)
eq9 = z + (vz * t3) == _sage_const_232302441670972  + (_sage_const_95  * t3)
eq10 = ans == x + y + z
print(solve([eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9,eq10],x,y,z,vx,vy,vz,t1,t2,t3,ans))

