PREFIX path: <http://www.ontotext.com/path#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX voc: <https://swapi.co/vocabulary/>

CONSTRUCT {
    ?startNode ?predicate ?endNode.
} WHERE {
    SERVICE path:search {
        [] path:findPath path:shortestPath ;
           path:sourceNode ?startNode ;
           path:destinationNode ?endNode ;
           path:propertyBinding ?predicate.
    }
}
