PREFIX : <>

SELECT ?n
WHERE {
    {
    ?c a :Characters ;
         :name ?n .
    }
    UNION
    {
    ?c a :Film ;
         :name ?n .
    }
    # If want to excluding some names
    MINUS {
        ?c :name "EXAMPLE NAME" .
    }
}
ORDER BY ASC(?n)