apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: app-pod
    app: demo-app
